### ISSUE TITLE
DLL missing

### ISSUE THREAD

**Issue by hello6798** [cerealwithmilk/Fluster#2]
When running it after its installed it gives the error "The code execution cannot proceed because CONCRT140_APP.dll was not found. Reinstalling the program may fix this problem." then with vccorlib140_app.dll, MSVCP140_APP.dll, and VCRUNTIME140_APP.dll.
i tried reinstalling multiple times. i forcefully permanently removed my antivirus and several other antivirus features, didnt work. i even have developer mode on

**Comment by ventrio** [comment]
whats ur discord i can try help u if u want

**Comment by hello6798** [comment]
> whats ur discord i can try help u if u want

my discord is aaj67 (i didnt like the username thing so i just put random letters and numbers as my discord name)

**Comment by hello6798** [comment]
all i really need is a way to fix it or the dll files to download

**Comment by cerealwithmilk** [comment]
@hello6789
@ventrio

The issues tab **is not for giving support** and rather than just be for development coding wise, that it's not even done yet.
Avoid giving each other support without knowing the other person and instead join the discord server for Fluster: https://discord.gg/cereal
